name: deploy-pages
on:
  push:
    branches: ["main"]
    paths-ignore:
      - .gitignore
      - LICENSE
      - README.md
      - .devcontainer/**
      - .github/**
      - "!.github/workflows/cmake-workflow-preset-docs.yml"
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
jobs:
  cmake-workflow-preset-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jwlawson/actions-setup-cmake@v2
      - uses: goto-bus-stop/setup-zig@v2
      - uses: actions/configure-pages@v5
      - run: cmake --workflow --preset docs
      - uses: actions/upload-pages-artifact@v3
        with:
          path: build/html
  deploy-pages:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deploy-pages.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - id: deploy-pages
        uses: actions/deploy-pages@v4
